apiVersion: v1
kind: Service
metadata:
  name: eureka-discovery-service-ip-service
spec:
  type: ClusterIP
  selector:
    component: eureka-discovery-service
  ports:
    - port: 8761
      targetPort: 8761
